apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: ex-208
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgres
