apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
  namespace: ex-206
spec:
  type: NodePort
  selector:
    app: logoutput
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
