apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  namespace: ex-207
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: pingpong:4.0
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: 'PROD'
          - name: DATABASE_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: application-configuration
                key: DATABASE_SERVER_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: DB_PASSWORD
