apiVersion: v1
kind: Service
metadata:
  name: imagefinder-svc
spec:
  type: NodePort
  selector:
    app: imagefinder
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
