apiVersion: v1
kind: Service
metadata:
  name: todolistservice-svc
  namespace: ex-208
spec:
  type: NodePort
  selector:
    app: todolistservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080


--- 

apiVersion: v1
kind: Service
metadata:
  name: todolistapp-svc
  namespace: ex-208
spec:
  type: NodePort
  selector:
    app: todolist-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
