apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stateful-application-ingress
  namespace: ex-207
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pingpong-svc
            port:
              number: 80
