apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: ex-207
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
