apiVersion: v1
kind: Secret
metadata:
    name: database-secrets
    namespace: ex-208
data:
    DB_USER: ENC[AES256_GCM,data:EX5sv0bk0W4=,iv:8Yz6uFpRysOOfzKjyhuq+jK0ZDTowuOSFBRJ3I/wrcY=,tag:19CjNet/4TRYsfEH9oYF+Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:a63eMwISXFvVW9Rg,iv:7tMmTrGRNKfuVtbaBca2kBw3AsPcKJwHPHhG6/a4fnU=,tag:YRw5nHU7ZTKgR+X7Xgf11A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e45e37x65anrsmdan2dpezj5rxnymp3afgzxm7p4f0538dehfuzqqpkfpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld2puUTVkZ2pmRjdtblBN
            WVI5Y2p6SkEwNXNKMDgyZFI1ekVva25XMTFRCjRIQ3ZmRzFjYWFNcW8zUGt6eTh6
            eFJMMkhheU9pc3dQV25qcEFFdWZUL0UKLS0tIDNwUWZCMjZ2WGVhUHdyQjdiMUEw
            L2N0WjlDaU1JUkhnOEZ1REZUb3grRTgKzcIypda7AXohKOYdxWf7oht3h/GNQ/Cp
            o2eiohhCBgxJoxv+3K6umj5a0r+GyjvKZ+5R3f7/9c16skvTiDFwdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T23:16:16Z"
    mac: ENC[AES256_GCM,data:HGOfrqtho1z8ostyVLJPOCtJ11FibW7s12bIX6JQUlZrKFUSPNckUUG7kFjxm7vMKM+59t/qK3VrbGbyReRc3YgPCIWG7Iy0HyA/h+76HM/F6+Ms9HjW2eStiipZBAZ8PtqJlwoeDmILI/FjavKn9WeY8kIP1WNGXljTwE6i5BA=,iv:ua4ZOmwuN09dFVwIi6cQfU1/VJUqdSnKAHhrrT7EUxg=,tag:P0jc+A85/2/Keg185qQ54g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
