apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: persistent-image-cache
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imagefinder-svc
            port:
              number: 80
